### PR TITLE
Add Fractional Rating

### PR DESCRIPTION
**Pull request by devmtnaing**
Hi,

Everything works great and all. 

I just needed to display the rating stars similar to amazon rating system where they allow fractional rating. 

So I added a few lines of code to your library to allow that feature. 

I hope this could be helpful. 

Best Regards,
Min

### CODE REVIEW

**Comment by NdYAG** [comment]
@devmtnaing Thank you for the idea and code!
Before I merge this pull request, would you mind rebasing these two commits into one?
Thank you very much!

**Comment by devmtnaing** [comment]
Hi @NdYAG 

It is now only one commit for the changes. 

It's very much my pleasure!

Cheers

**Comment by NdYAG** [comment]
LGTM, thank you !

**Comment by NdYAG** [comment]
Hey @devmtnaing 

It's now published as 0.3.5, 

and you don't have to add `fraction` prop, since `>= 0.5 && < 1` is enough to prove that the rating value is not an integer. In this way we keep the interface simple, but works stronger.

Thanks again, you can update your packages.json right now.

**Comment by devmtnaing** [comment]
Hey @NdYAG  

Ya sure, it works too. 👍  

I put it just in case a developer doesn't round up the calculated total rating to integer and they still also doesn't want fractional rating.

Cool. updating now. Thanks.

**Pull request merged**
